### ISSUE TITLE
Add or remove close friends from the friendpile

### ISSUE THREAD

**Issue by piperchester** [piperchester/besties#10]
I think it'd be cool to quickly be able to add or remove friends after you scrape. By hovering over the div, and X would appear and you could drop the close friend

**Comment by nateperry** [comment]
It would just remove them from the list? Or would it actually remove them from your Close Friends?

**Comment by piperchester** [comment]
Remove from Close Friends. Thoughts?

**Comment by nateperry** [comment]
If the API gives us that ability, then yea, I like that idea

**Comment by piperchester** [comment]
[Yep](https://developers.facebook.com/docs/graph-api/reference/friendlist/members/). Going to work on that now

**Comment by piperchester** [comment]
Not sure what the issue is. Returning error code 100, invalid parameter. Could be an issue with the API. Blocked for now

**Comment by piperchester** [comment]
Looks like this just isn't possible anymore with the [new API](https://developers.facebook.com/docs/graph-api/reference/v2.0/friendlist). Closing for now as not implemented.
