### ISSUE TITLE
Popover for Facebook IDs

### ISSUE THREAD

**Issue by piperchester** [piperchester/besties#3]
A lot of people don't know what a Facebook ID is. Until we have some other functionality like 'search for friends' I thought it'd be nice to have a popover under the input form explaining what it is.

Thoughts?

**Comment by nateperry** [comment]
I just pushed a commit that will take in the signed in user and scrape using the current users code. I don't think that we can scrape using someone elses code. At least I have not been able to

**Comment by piperchester** [comment]
Nice! We don't need a popover then. Closing the issue.
